spring:
  application:
    name: Kotlin API
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin
    username: hangalito
    password: jds
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
