spring:
  application:
    name: Kotlin API
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
